image: qasico/go:latest

before_script:
  - go version
  - mkdir $GOPATH/src/github.com/env-io
  - mkdir $GOPATH/src/github.com/env-io/cuxs
  - WD="$GOPATH/src/github.com/env-io/cuxs/env"

test:
  script:
    - "cp -R $(pwd) $WD && cd $WD"
    - gotest
